name: 'Google APIs Script'
description: 'Run simplet scripts using the Google APIs client'
inputs:
  script:
    required: true
    description: 'The script to run'
  service-account-credentials-json:
    required: false
    description: 'JSON content of Service Account Credentials'
  scopes-json:
    required: false
    description: 'API scopes in JSON represetion '
runs:
  using: 'node12'
  main: 'dist/index.js'
