name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  serviceAccountCredentialsJson:
    required: false
    description: 'JSON content of Service Account Credentials'
  scopesJson:
    required: false
    description: 'API scopes in JSON represetion '
runs:
  using: 'node12'
  main: 'dist/index.js'
